### ISSUE TITLE
[Extra] .github의 md파일 인코딩 문제

### ISSUE THREAD

**Issue by pkoi5088** [CSID-DGU/2023-02-CECD2-6#1]
## 주요 내용
.github폴더안에 있는 .md파일의 한글 인코딩 문제를 발견, 발견된 파일은 다음과 같음
* ISSUE_TEMPLATE/
  * bug-report.md
  * experiment.md
  * extra.md
  * feature-development.md
  * feature-request.md
  * README.md
* commit_template_manual.md
* pull_request_template.md

## 추가 설명
문제가 발견된 상황의 인코딩 환경은 **'UTF-8'** 이며 **'EUC-KR'** 로 바꾸면 정상적으로 한글이 보이는 것으로 보아 인코딩 환경의 통일이 필요할 것으로 예상됨

**Comment by pkoi5088** [comment]
아 그리고 md파일 수정하면서 .gitignore도 추가해주시면 감사합니다.

**Comment by sooya233** [comment]
처리 완료했습니다.
