### ISSUE TITLE
[Feat] 중복 뉴스 기사 생략 기능 구현

### ISSUE THREAD

**Issue by pkoi5088** [CSID-DGU/2023-02-CECD2-6#10]
## 추가 기능
newsGenerator의 중복 뉴스 기사 생략 기능

## 추가 목적
newsGenerator 모듈의 반복 실행으로 발생하는 중복 뉴스 크롤링을 생략함으로 실행 시간을 줄이기 위함

## 구현 방법
1. newsGenerator의 마지막 단계로 기사 주제마다 '최신 기사의 포스팅 시간대'를 저장(Json)하는 단계를 추가
2. newsGenerator는 RSS를 가져오기 전 이전 실행에서 생성된 최신 기사에 대한 정보를 불러옴
3. 기사를 크롤링하기전에 해당 기사의 포스팅 시간을 확인
4. 이미 이전 실행에서 가져온 기사라면 크롤링을 하지 않는다.

**Comment by pkoi5088** [comment]
RSS에서 기사 포스팅 시간을 가져오려고 하는데 이후에 DB에 넣어야 될 상황이 생긴다면 DB에 넣기 쉬운 형식으로 바꾸는게 좋을 것 같습니다. 어떤 형식이 편할까요?

지금 형식은 `Sun, 24 Sep 2023 10:50:41 +0000` 처럼 ***RFC 2822***형식을 따르고 있습니다. Postgresql에서 찾아보니까 `to_timestamp('2023-09-24 10:50:41', 'YYYY-MM-DD HH24:MI:SS')`같은 예제가 있는데 `2023-09-24 10:50:41` 형식으로 하는 것도 좋을 것 같습니다.

@sooya233

**Comment by sooya233** [comment]
DB에 저장할때, 최대한 postgresql의 timestamp 형식에 맞춰서 저장하는것을 추천합니다.
python에서 db에 저장할때 자동으로 변환이 되는지는 살펴봐야겠지만, 일단은 형식을 HH:MM:SS 형식으로 맞춰서 저장하는것을 추천합니다.
