### ISSUE TITLE
[Bug] RSS 실행 시 lastPost.json 파일 오류

### ISSUE THREAD

**Issue by sooya233** [CSID-DGU/2023-02-CECD2-6#19]
## 버그 설명
RSS를 실행할 때, 이전 호출의 시간을 기록하는 lastPost.json파일이 존재한다.
그러나, 해당 파일이 추적이 불가하여 현재는 newsdata.py파일 실행 자체가 불가하다.

## 에러 메시지
FileNotFoundError: [Errno 2] No such file or directory: './RSS/lastPost.json'

## Screenshots
<img width="874" alt="image" src="https://github.com/CSID-DGU/2023-02-CECD2-6/assets/71958885/dcc4a9bc-4d7c-4134-b39a-7dd07e426be3">

**Comment by sooya233** [comment]
@pkoi5088

**Comment by pkoi5088** [comment]
알려주신 버그 수정을 완료했습니다. 한번 확인해주세요

1.  RSS/lastPost.json이 없는 상황에서
2. testNewsGenerator.py 또는 newsdata.py를 통해 RSS 모듈을 사용
3. 기존에 발생하면 에러가 발생하는지  확인

**Comment by sooya233** [comment]
정상적으로 작동하는거 확인했습니다. 이슈 닫을게요
